### ISSUE TITLE
Links to schema file and live sample require sign in 

### ISSUE THREAD

**Issue by TifPun** [Esri/solutions-geoevent-java#44]
From the [Weather sample](https://github.com/Esri/solutions-geoevent-java/tree/master/data/weather) there is a link to download the schema and another link to open the live sample. However, when I click on the links I was prompted to sign in. 

![image](https://cloud.githubusercontent.com/assets/4983864/6511873/8f30ced0-c324-11e4-8a0e-b3e7c6e9e737.png)

Will be great if the URLs could be made public.

**Comment by pHill5136** [comment]
These links are on an old Portal instance. @dmMartin can you check into this and see if we can provide the schema in the data folder on github?

**Comment by jrweakland** [comment]
@abrowning80 - please verify with @dmMartin

**Comment by abrowning80** [comment]
@jrweakland @pHill5136 I now have the info from David Martin about this and am hoping to start work tomorrow. As these should be geodatabases is GiTHUB the right place to be putting these as original best practice was not to put data up here as far as we thought.

**Comment by csmoore** [comment]
Not sure what category this data is, but in general for GIS Data:

1. Data that is required to run the software - should be included with the software on Github ( [example](https://github.com/Esri/solutions-geoprocessing-toolbox/tree/master/visibility/toolboxes/tooldata/VisibilityandRange.gdb)
2. Sample or test data - should go on ArcGIS Online as public items

**Comment by abrowning80** [comment]
@pHill5136 Have created pull request please check and come back to me with any updates required.

**Comment by pHill5136** [comment]
Closing this is resolved
