### ISSUE TITLE
Issues with mvn install with 10.3.1

### ISSUE THREAD

**Issue by slibby** [Esri/solutions-geoevent-java#47]
after following all setup instructions and cloning this repository, this is the output of ```mvn install``` includes a bunch of errors.

I know that some files need to be changed from ```10.3.0``` to ````10.3.1``` but it seems like there are deeper issues with names changing. 

Has anyone validated the build processes with 10.3.1 GES?

**Comment by pHill5136** [comment]
What kind of errors? The components have been tested at 10.3.1. Typically errors building in maven happen when maven cannot resolve the paths to the repository and system files and if the version in the pom is not the same as the version of the internal repository.

**Comment by slibby** [comment]
I believe that the "typical" errors are what I'm seeing, but there is not any guidance that I can see on where to update the version numbers and paths. I am running on windows, so for example, I believe the right path is 
```<url>file:///C:/Program%20Files/ArcGIS/Server/GeoEvent/sdk/repository</url>```
instead of 
```<url>file:///geoevent-10.3.1.4271/geoevent-10.3.1/sdk/repository</url>```

But should this be changed in every pom.xml file?

**Comment by pHill5136** [comment]
Sam,

Do you remember which pom you saw the repo ref to
file:///geoevent-10.3.1.4271/geoevent-10.3.1/sdk/repository<file:///\\geoevent-10.3.1.4271\geoevent-10.3.1\sdk\repository>?
That is an artifact from using daily builds…

I’ll go through and check the paths…

**Comment by slibby** [comment]
https://github.com/Esri/solutions-geoevent-java/blob/5214186f8c9430085c8170e76e71c3b0ae524833/solutions-geoevent/pom.xml

**Comment by pHill5136** [comment]
I have modified a few of the paths to repositories in the poms. In some cases they still pointed to daily build locations.

**Comment by jrweakland** [comment]
@pHill5136 - Is this ready for @slibby to verify and close?

**Comment by slibby** [comment]
@pHill5136 I re-cloned the repo and simply did ```mvn install``` and here's the output: https://gist.github.com/slibby/078d9599a205b8cf01b8

**Comment by pHill5136** [comment]
@slibby I changed back the main pom.xml to 10.3.0 because all of the internal poms were referencing 10.3.0 -- and so wouldn't build. If you have 10.3.1 installed I think you can just change that in your pom (individual and external). If you are just building a few components I would build them separately. I will be updating the poms to 10.3.1 sometime this week.

**Comment by pHill5136** [comment]
@slibby One other thing to complicate moving to 10.3.1 - the library declaration has changed slightly

You should use the following for the ges library dependency tag in the pom

```
<dependency>
			<groupId>com.esri.ges.sdk</groupId>
			<artifactId>ges-lib</artifactId>
			<version>10.3.0</version>
		</dependency>
```

**Comment by pHill5136** [comment]
@slibby Sorry, accidentally sent too soon with the old tag... Dangers of copy paste. This is the tag in the pom. You may want to check the paths in your distribution of geoevent. I typically install from a zipfile on the daily builds. This is how the path is set up in those for GEE 10.3.1 final.

```
        <dependency>
            <groupId>com.esri.geoevent.sdk</groupId>
            <artifactId>geoevent-sdk</artifactId>
            <version>10.3.1</version>
        </dependency>
```

**Comment by pHill5136** [comment]
Added 10.3.1 compliant poms
