### ISSUE TITLE
MGRS Processor

### ISSUE THREAD

**Issue by jrweakland** [Esri/solutions-geoevent-java#48]
There is a need for a MGRS Processor. User story: When a missile launch occurs, users need to have lat/long and MGRS location for the launch point.

**Comment by csmoore** [comment]
If something like this doesn't already exist for GeoEvent or this repo - you might want to have a processor that provides a generic coordinate conversion utility like exists in the ArcGIS Runtime CoordinateConversion class: https://developers.arcgis.com/android/api-reference/reference/com/esri/core/geometry/CoordinateConversion.html

**Comment by jrweakland** [comment]
https://app.asana.com/0/22926133759983/43808146567926
