### ISSUE TITLE
Pathnames too long for Windows to unzip

### ISSUE THREAD

**Issue by jfrygeo** [Esri/solutions-geoevent-java#57]
Trying to extract files to C:\  and getting "Path name too long" error, making the zip file unable to unzip. Used 7-zip and looks like files are unzipped properly.

**Comment by csmoore** [comment]
Is this using the "Download Zip" from Github? You can also clone the repo using [Github Desktop](https://desktop.github.com/) if you want to avoid using the zipped repo. 

I suspect the only difference between Windows zip and 7zip is Windows in inserting an extra "solutions-geoevent-java-xxxx" folder

**Comment by topowright** [comment]
I have also seen this issue with the zip file that we have posted on the Solutions Site
@pHill5136 do you know about this?

**Comment by csmoore** [comment]
The 260 windows file length limit is the bane of Java deployments everywhere - for this particular deployment not including the whole repo/source (just the deployment jars) in the download item might help.

For the technical details, this is not a strict Windows OS limit, but a limitation of apps that use the Win32 API.
