### ISSUE TITLE
Misnamed file

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-geoevent-java#58]
Related to https://github.com/ArcGIS/arcgis-solutions-website/issues/3093

https://github.com/Esri/solutions-geoevent-java/blob/master/solutions-geoevent/resources/10.4.0/bearing-processor-10.4%2C0.jar has a comma instead of a period (10.4,0 instead of 10.4.0)

Incidentally, I think it's just 10.4.

**Comment by pHill5136** [comment]
@joebayles 
for the jar files we use 10.4.0 because there are rules for the building of jars using maven -- which is what geoevent uses for builds and to be consistent with geoevent gallery items. I fixed the jar name and the link works now.

**Comment by joebayles** [comment]
Verified, thanks
