### ISSUE TITLE
Update Only Processor stopped working

### ISSUE THREAD

**Issue by DineshAtPowel** [Esri/solutions-geoevent-java#67]
The update only process version 10.5 stopped working and shows error GeoEventProcessor(uri=com.esri.geoevent.solutions.processor.updateOnly/UpdateOnlyProcessor/10.5.0) is not available.

Tried redeploying, restarting services and restarting server. But, none of it helped.

Regards
Dinesh Mathur

**Comment by pHill5136** [comment]
@DineshAtPowel Did it stop working after you updated to 10.5? You may have to recreate the connector.

**Comment by DineshAtPowel** [comment]
Yes, it stopped after updating to 10.5. I have tried recreating the connector that also did not work.
We stopped using 10.5 and reverted back to older version.
