### ISSUE TITLE
GE: TCP Squirt transport

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-geoevent-java#88]
- [ ] add deprecation banner to landing page
- [ ]  add deprecation banner to github readme
- [ ] remove links to page (solutions site)
- [ ] update what's new

**Comment by NatalieCampos** [comment]
Removing my assignment of TCP transport.  In the 10/9 scrum, @pHill5136 stated this component should be deprecated and that he will discuss that possibility with @lfunkhouser.
